---
- name: Configure Samba and Bind
  hosts: all
  become: yes
  tasks:
    - name: Update Cache
      command: apt-get update
      
    - name: Install task-samba-dc bind bind-utils
      command: apt-get install -y task-samba-dc bind bind-utils
      
    - name: Stop and disable services
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - bind
        - krb5kdc
        - nmb
        - smb
        - slapd
      ignore_errors: yes

    - name: Clean Samba configuration
      file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
      loop:
        - { path: '/etc/samba/smb.conf', state: 'absent' }
        - { path: '/var/lib/samba', state: 'absent' }
        - { path: '/var/cache/samba', state: 'absent' }
        - { path: '/var/lib/samba/sysvol', state: 'directory', mode: '0755' }

    - name: Disable bind chroot
      command: control bind-chroot disabled

    - name: Configure KRB5RCACHETYPE
      lineinfile:
        path: /etc/sysconfig/bind
        regexp: '^KRB5RCACHETYPE='
        line: 'KRB5RCACHETYPE="none"'
        state: present

    - name: Add bind-dns include
      lineinfile:
        path: /etc/bind/named.conf
        line: 'include "/var/lib/samba/bind-dns/named.conf";'
        regexp: 'include ".*bind-dns/named.conf"'
        state: present

    - name: Configure options section
      blockinfile:
        path: /etc/bind/options.conf
        marker: "# {mark} ANSIBLE MANAGED OPTIONS"
        block: |
          tkey-gssapi-keytab "/var/lib/samba/bind-dns/dns.keytab";
          minimal-responses yes;
        insertafter: '^options {'

    - name: Configure logging section
      blockinfile:
        path: /etc/bind/options.conf
        marker: "# {mark} ANSIBLE MANAGED LOGGING"
        block: |
          category lame-servers {null;};
        insertafter: '^logging {'

    - name: Update network parameters
      replace:
        path: /etc/bind/options.conf
        regexp: '^(\s*)(//\s*)?(allow-query|allow-recursion|listen-on)(\s+.*;)'
        replace: '\1\3 { any; };'

- name: Promote samba-dc1 to PDC
  hosts: samba-dc1
  become: yes
  tasks:
    - name: Provision Samba Domain
      command: samba-tool domain provision 
        --realm=au-team.irpo 
        --domain=au-team
        --adminpass='P@ssw0rd' 
        --dns-backend=BIND9_DLZ 
        --server-role=dc
      args:
        creates: /etc/samba/smb.conf  # Защита от повторного выполнения

    - name: Disable DNS in samba config
      blockinfile:
        path: /etc/samba/smb.conf
        marker: "# {mark} ANSIBLE MANAGED SERVER SERVICES"
        block: |
          server services = -dns
        insertafter: '^\[global\]'

    - name: Start and enable Samba
      service:
        name: samba
        state: started
        enabled: yes

    - name: Start and enable Bind9
      service:
        name: bind
        state: started
        enabled: yes

- name: Add samba-dc2 to DNS on domain
  hosts: samba-dc1
  become: yes
  tasks:
    - name: Add record
      command: samba-tool dns add 127.0.0.1 au-team.irpo samba-dc2 A {% for host in groups['samba-dc2'] %}
                {{ hostvars[host].ansible_default_ipv4.address }}
               {% endfor %} -U administrator%P@ssw0rd 

- name: Add samba-dc2 to domain as dc
  hosts: samba-dc2
  become: yes
  tasks:
    - name: Backup resolv.conf
      copy:
        remote_src: yes
        src: /etc/resolv.conf
        dest: /etc/resolv.conf.bak
        force: yes

    - name: Configure resolv.conf with DC1 DNS
      copy:
        content: |
          nameserver {% for host in groups['samba-dc1'] %}{{ hostvars[host].ansible_default_ipv4.address }}{% endfor %}
        dest: /etc/resolv.conf
        force: yes

    - name: Configure Kerberos settings
      blockinfile:
        path: /etc/krb5.conf
        marker: "# {mark} ANSIBLE MANAGED KRB5 CONFIG"
        block: |
          [libdefaults]
            default_realm = AU-TEAM.IRPO
            dns_lookup_realm = false
            dns_lookup_kdc = true
        insertafter: '^\[libdefaults\]'
        mode: 0644

    - name: Obtain Kerberos ticket
      command: kinit administrator@AU-TEAM.IRPO
      args:
        stdin: "P@ssw0rd\n"
      no_log: false
      changed_when: false

    - name: Join domain
      command: samba-tool domain join au-team.irpo DC -Uadministrator%P@ssw0rd --realm=au-team.irpo --dns-backend=BIND9_DLZ

    - name: Disable DNS in samba config
      blockinfile:
        path: /etc/samba/smb.conf
        marker: "# {mark} ANSIBLE MANAGED SERVER SERVICES"
        block: |
          server services = -dns
        insertafter: '^\[global\]'
        before: '^\[[^\]]+\]'

    - name: Restore original resolv.conf
      copy:
        src: /etc/resolv.conf.bak
        dest: /etc/resolv.conf
        remote_src: yes
        force: yes

    - name: Start and enable Samba
      service:
        name: samba
        state: started
        enabled: yes

    - name: Start and enable Bind9
      service:
        name: bind
        state: started
        enabled: yes
